/* Generated by scripts/dither.mjs from images.manifest.json — do not edit. */
export const imagesHash = '63bdcf56';

export type Tone = "paper" | "crimson" | "rose" | "ink";
export type ImageVariant = `${Tone}` | `${Tone}-dense`;
export interface ImageCredit {
  title: string;
  author: string;
  year: number | null;
  licence: string;
  licence_url: string;
  page_url: string;
  source: string;
}
export interface GeneratedImage {
  alt: string;
  aspect: number;
  variants: Partial<Record<ImageVariant, Record<number, string>>>;
  credit: ImageCredit;
}

export const images = {
  "corbeau": {
    "alt": "A large raven, hunched on cobblestones, staring straight at the viewer. Etching.",
    "aspect": 1.1538461538461537,
    "variants": {
      "crimson": {
        "720": "images/corbeau-720-crimson.png",
        "1440": "images/corbeau-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/corbeau-720-crimson-dense.png",
        "1440": "images/corbeau-1440-crimson-dense.png"
      },
      "paper": {
        "720": "images/corbeau-720-paper.png",
        "1440": "images/corbeau-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/corbeau-720-paper-dense.png",
        "1440": "images/corbeau-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Le Corbeau",
      "author": "Félix Bracquemond",
      "year": 1854,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_DP814037.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "bust": {
    "alt": "A raven perched on a marble bust of Pallas, a halo of faces behind it. Wood engraving.",
    "aspect": 0.6986899563318777,
    "variants": {
      "paper": {
        "720": "images/bust-720-paper.png",
        "1440": "images/bust-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/bust-720-paper-dense.png",
        "1440": "images/bust-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Perched upon a bust of Pallas (The Raven, plate 15)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:Paul_Gustave_Dore_Raven15.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "door": {
    "alt": "A tall double door standing ajar, a figure half visible in the gap, light pouring through. Wood engraving.",
    "aspect": 0.6672845227062094,
    "variants": {
      "paper": {
        "720": "images/door-720-paper.png",
        "1440": "images/door-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/door-720-paper-dense.png",
        "1440": "images/door-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Here I opened wide the door (The Raven)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_MM61687.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "lamp": {
    "alt": "A man reading at a table by lamplight, a child asleep against him. Wood engraving.",
    "aspect": 0.7663650878126663,
    "variants": {
      "paper": {
        "720": "images/lamp-720-paper.png",
        "1440": "images/lamp-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/lamp-720-paper-dense.png",
        "1440": "images/lamp-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "Over many a quaint and curious volume (The Raven, plate 2)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:Paul_Gustave_Dore_Raven2.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "nevermore": {
    "alt": "A raven flying out from behind a heavy curtain that a figure is pulling aside; a banner reads Nevermore. Wood engraving.",
    "aspect": 0.9842788790157211,
    "variants": {
      "paper": {
        "720": "images/nevermore-720-paper.png",
        "1440": "images/nevermore-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/nevermore-720-paper-dense.png",
        "1440": "images/nevermore-1440-paper-dense.png"
      },
      "crimson": {
        "720": "images/nevermore-720-crimson.png",
        "1440": "images/nevermore-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/nevermore-720-crimson-dense.png",
        "1440": "images/nevermore-1440-crimson-dense.png"
      }
    },
    "credit": {
      "title": "Nevermore (The Raven)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_MM89635.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "moon": {
    "alt": "A veiled figure with a scythe seated on the moon among clouds, a raven flying beneath. Wood engraving.",
    "aspect": 1.1145510835913313,
    "variants": {
      "paper": {
        "720": "images/moon-720-paper.png",
        "1440": "images/moon-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/moon-720-paper-dense.png",
        "1440": "images/moon-1440-paper-dense.png"
      },
      "crimson": {
        "720": "images/moon-720-crimson.png",
        "1440": "images/moon-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/moon-720-crimson-dense.png",
        "1440": "images/moon-1440-crimson-dense.png"
      }
    },
    "credit": {
      "title": "Frontispiece to The Raven",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_MM61688.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "shore": {
    "alt": "Two framed panels: a sleeping figure among waves, and a raven over a dark sea beneath cliffs; the caption reads The Night's Plutonian Shore. Pen drawing.",
    "aspect": 1.4131501472031402,
    "variants": {
      "crimson": {
        "720": "images/shore-720-crimson.png",
        "1440": "images/shore-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/shore-720-crimson-dense.png",
        "1440": "images/shore-1440-crimson-dense.png"
      },
      "paper": {
        "720": "images/shore-720-paper.png",
        "1440": "images/shore-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/shore-720-paper-dense.png",
        "1440": "images/shore-1440-paper-dense.png"
      }
    },
    "credit": {
      "title": "The Night's Plutonian Shore",
      "author": "William Heath Robinson",
      "year": 1909,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:%22The_Night%27s_Plutonian_Shore%22-_The_Raven_MET_DP821071.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "huginn": {
    "alt": "A raven in flight, wings spread, cropped from Doré's Nevermore plate.",
    "aspect": 1.3495782567947516,
    "variants": {
      "paper": {
        "720": "images/huginn-720-paper.png",
        "1440": "images/huginn-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/huginn-720-paper-dense.png",
        "1440": "images/huginn-1440-paper-dense.png"
      },
      "crimson": {
        "720": "images/huginn-720-crimson.png",
        "1440": "images/huginn-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/huginn-720-crimson-dense.png",
        "1440": "images/huginn-1440-crimson-dense.png"
      }
    },
    "credit": {
      "title": "Nevermore (detail: the raven)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_MM89635.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  },
  "muninn": {
    "alt": "A raven gliding beneath the moon, cropped from Doré's frontispiece to The Raven.",
    "aspect": 1.254355400696864,
    "variants": {
      "paper": {
        "720": "images/muninn-720-paper.png",
        "1440": "images/muninn-1440-paper.png"
      },
      "paper-dense": {
        "720": "images/muninn-720-paper-dense.png",
        "1440": "images/muninn-1440-paper-dense.png"
      },
      "crimson": {
        "720": "images/muninn-720-crimson.png",
        "1440": "images/muninn-1440-crimson.png"
      },
      "crimson-dense": {
        "720": "images/muninn-720-crimson-dense.png",
        "1440": "images/muninn-1440-crimson-dense.png"
      }
    },
    "credit": {
      "title": "Frontispiece to The Raven (detail: the raven)",
      "author": "Gustave Doré",
      "year": 1884,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:The_Raven_MET_MM61688.jpg",
      "source": "The Metropolitan Museum of Art, Open Access"
    }
  }
} as const satisfies Record<string, GeneratedImage>;

export type ImageId = keyof typeof images;
